import { VercelRequest, VercelResponse } from '@vercel/node';
import { Redis } from '@upstash/redis';
import { search } from './vector/search';
import { generateEmbedding } from './utils/embeddings';
import { generateContent } from './utils/gemini';

const POLICY_DISPLAY: Record<string, string> = {
  public: 'Public — Open to all',
  sietch_secret: 'Sietch Secret — Fremen only',
  imperial_classified: 'Imperial Classified — No access'
};

const ROLE_DISPLAY: Record<string, string> = {
  fremen: 'Fremen',
  smuggler: 'Smuggler',
  imperial_spy: 'Imperial Spy'
};

const ROLE_PREFIXES: Record<string, string> = {
  fremen: 'The desert speaks through the spice... ',
  smuggler: "Smuggler's log indicates... ",
  imperial_spy: 'Imperial records show... '
};

const IDENTITY_ROLES: Record<string, string> = {
  paul: 'fremen',
  gurney: 'smuggler',
  harkonnen: 'imperial_spy'
};

function checkPermission(userRole: string, filePolicy: string): boolean {
  switch (filePolicy) {
    case 'public': return true;
    case 'sietch_secret': return userRole === 'fremen';
    case 'imperial_classified': return userRole === 'imperial_spy';
    default: return false;
  }
}

function getRedis(): Redis {
  const url = process.env.UPSTASH_REDIS_REST_URL;
  const token = process.env.UPSTASH_REDIS_REST_TOKEN;
  
  if (!url || !token) {
    throw new Error('Upstash Redis credentials not configured');
  }
  
  return new Redis({ url, token });
}

interface QueryRequest {
  query: string;
  identity: string;
  fileId?: string;
  policy?: string;
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const startTime = Date.now();

  try {
    const body = req.body as QueryRequest;
    const { query, identity, fileId, policy } = body;

    if (!query || !identity) {
      return res.status(400).json({ error: 'Missing query or identity' });
    }

    const userRole = IDENTITY_ROLES[identity] || 'fremen';
    const userRoleDisplay = ROLE_DISPLAY[userRole];
    const prefix = ROLE_PREFIXES[userRole] || '';

    let targetPolicy = policy;
    let targetFileId = fileId;

    if (!targetFileId) {
      return res.status(400).json({ error: 'No file specified. Please ingest a file first.' });
    }

    if (!targetPolicy) {
      targetPolicy = 'public';
    }

    const authorized = checkPermission(userRole, targetPolicy);

    if (!authorized) {
      const denialMessage = `ACCESS DENIED BY SPICEDB: Missing relation 'viewer' on resource '${targetFileId}' (policy: ${POLICY_DISPLAY[targetPolicy]}) for subject 'user:${identity}' (role: ${userRoleDisplay})`;
      
      return res.status(403).json({
        error: 'Permission denied',
        message: denialMessage,
        authorized: false,
        policy: targetPolicy,
        role: userRoleDisplay
      });
    }

    const queryEmbedding = await generateEmbedding(query);

    const redis = getRedis();
    const results = await search(redis, queryEmbedding, {
      k: 4,
      fileId: targetFileId,
      policy: targetPolicy
    });

    if (results.length === 0) {
      const response = `${prefix}<strong>No relevant chunks retrieved from the Spice Vault. No relevant information found in the ingested documents.</strong><br><em>— SpiceDB authorization verified. Relation 'viewer' confirmed on resource '${targetFileId}' for ${userRoleDisplay}.</em>`;
      
      return res.status(200).json({
        answer: response,
        sources: [],
        authorized: true,
        fileId: targetFileId,
        policy: targetPolicy,
        latencyMs: Date.now() - startTime
      });
    }

    const contextChunks = results.map((r: any, i: number) => 
      `[${i + 1}] <em>${r.metadata.contentType || 'text_prose'}</em> — "${r.text.slice(0, 200).replace(/\n/g, ' ')}..."`
    ).join('<br>');

    const contextText = results.map((r: any, i: number) => 
      `--- Context Source ${i + 1} (${r.metadata.contentType || 'text_prose'}) ---\n${r.text}`
    ).join('\n\n');

    const systemPrompt = `You are a rigorous, grounded research assistant. Answer the user's question using ONLY the provided context chunks below. The chunks contain text, explicitly parsed markdown tables, and detailed descriptions of figures generated by a vision model. If the answer cannot be directly derived from the context, state clearly that you do not have sufficient information.`;

    const userPrompt = `Context Material:\n${contextText}\n\nUser Question: ${query}`;

    const fullResponse = await generateContent(
      `${systemPrompt}\n\n${userPrompt}`,
      { temperature: 0.3, maxTokens: 2048 }
    );

    const response = `${prefix}<strong>Retrieved Context:</strong><br>${contextChunks}<br><br>${fullResponse}<br><br><em>— SpiceDB authorization verified. Relation 'viewer' confirmed on resource '${targetFileId}' for ${userRoleDisplay}.</em>`;

    return res.status(200).json({
      answer: response,
      sources: results.map((r: any) => ({
        id: r.id,
        score: r.score,
        text: r.text.slice(0, 500),
        metadata: r.metadata
      })),
      authorized: true,
      fileId: targetFileId,
      policy: targetPolicy,
      latencyMs: Date.now() - startTime
    });

  } catch (error: any) {
    console.error('Query error:', error);
    return res.status(500).json({ error: error.message || 'Internal server error' });
  }
}